const c=document.getElementById('game'),x=c.getContext('2d'),W=1280,H=720,G=590;
const K={left:0,right:0,jump:0,hit:0,throw:0},P={x:280,y:G,vx:0,vy:0,face:1,hp:5,beer:6,atk:0,score:0},Z=[],B=[],FX=[];let play=0,t=0,cam=0,shake=0;
const A={bg:new Image(),run:[],attack:[],z:[]};A.bg.src='assets/production/backgrounds/level1_backlot.webp';
for(let i=0;i<8;i++){A.run[i]=new Image();A.run[i].src='assets/production/whomper/run_'+String(i).padStart(2,'0')+'.png';A.attack[i]=new Image();A.attack[i].src='assets/production/whomper/attack_'+String(i).padStart(2,'0')+'.png'}
for(let i=0;i<4;i++){A.z[i]=new Image();A.z[i].src='assets/production/zombies/zombie_'+String(i).padStart(2,'0')+'.png'}
function reset(){Z.length=B.length=FX.length=0;Object.assign(P,{x:280,y:G,vx:0,vy:0,face:1,hp:5,beer:6,atk:0,score:0});for(let i=0;i<8;i++)Z.push({x:800+i*205,y:G,hp:3,hit:0,dead:0,type:i%4,phase:i*.8,kx:0,ky:0,kv:0,rot:0,stun:0})}
function bg(){if(!A.bg.naturalWidth)return;let s=Math.max(W/A.bg.naturalWidth,H/A.bg.naturalHeight),dw=A.bg.naturalWidth*s,dh=A.bg.naturalHeight*s;x.drawImage(A.bg,(W-dw)/2-cam*.12,(H-dh)/2,dw,dh)}
function sprite(im,px,py,w,h,flip=1,rot=0){if(!im||!im.naturalWidth)return;x.save();x.translate(px+(flip<0?w:0),py);x.scale(flip,1);x.rotate(rot);x.drawImage(im,0,0,w,h);x.restore()}
function hero(){let moving=Math.abs(P.vx)>.1&&P.y===G,frame=moving?Math.floor(t/5)%8:0,im=P.atk?A.attack[Math.min(7,Math.floor((16-P.atk)/2))]:A.run[frame];let bob=moving?Math.sin(t*.5)*3:0;sprite(im,P.x-cam-125,P.y-300+bob,250,300,P.face)}
function zombie(z){if(z.dead)return;let w=225,h=325,hit=z.hit>0,lean=hit?z.rot:Math.sin(t*.055+z.phase)*.012,bob=hit?z.ky:0;x.save();if(hit){x.filter='brightness(1.35) saturate(1.25)';x.globalAlpha=.96}sprite(A.z[z.type],z.x-cam-w/2,z.y-h+bob,w,h,z.x>P.x?-1:1,lean);x.restore()}
function pop(n,px,py){FX.push({n,x:px,y:py,l:38});shake=12}
function update(){if(!play)return;P.vx=(K.right-K.left)*7.5;if(P.vx)P.face=Math.sign(P.vx);P.x=Math.max(120,Math.min(3000,P.x+P.vx));if(K.jump&&P.y===G){P.vy=-15;K.jump=0}P.vy+=.8;P.y+=P.vy;if(P.y>G){P.y=G;P.vy=0}if(K.hit&&!P.atk){P.atk=16;K.hit=0}if(P.atk)P.atk--;if(K.throw&&P.beer){P.beer--;B.push({x:P.x+P.face*55,y:P.y-145,v:14*P.face,r:0});K.throw=0}
for(const z of Z){if(z.dead)continue;let d=P.x-z.x;if(z.stun>0)z.stun--;else if(Math.abs(d)<680)z.x+=Math.sign(d)*1.25;if(z.kx){z.x+=z.kx;z.kx*=.78;if(Math.abs(z.kx)<.2)z.kx=0}if(z.hit){z.ky+=z.kv;z.kv+=1.15;if(z.ky>0){z.ky=0;z.kv=0}}if(P.atk===7&&Math.abs(z.x-(P.x+P.face*95))<150){z.hp--;z.hit=16;z.stun=20;z.kx=P.face*13;z.ky=-18;z.kv=-5;z.rot=P.face*.16;P.score+=125;pop(z.hp?'WHOMP!':'K.O.!',z.x,z.y-190);if(z.hp<=0){z.hit=26;setTimeout(()=>z.dead=1,280)}}if(z.hit){z.hit--;z.rot*=.9}if(Math.abs(d)<50&&Math.random()<.008){P.hp--;z.x-=Math.sign(d)*70;shake=8;if(P.hp<=0){play=0;setTimeout(()=>{reset();play=1},1000)}}}
for(const b of B){b.x+=b.v;b.r+=.4;for(const z of Z)if(!z.dead&&Math.abs(b.x-z.x)<45){z.hp--;z.hit=15;z.stun=18;z.kx=Math.sign(b.v)*9;z.ky=-12;z.kv=-3.5;z.rot=Math.sign(b.v)*.12;b.x=-999;P.score+=125;pop('BONK!',z.x,z.y-185);if(z.hp<=0){z.hit=24;setTimeout(()=>z.dead=1,260)}}}cam=Math.max(0,Math.min(1720,P.x-380))}
function beer(b){x.save();x.translate(b.x-cam,b.y);x.rotate(b.r);x.fillStyle='#e7d7ad';x.strokeStyle='#20130c';x.lineWidth=4;x.fillRect(-10,-20,20,40);x.strokeRect(-10,-20,20,40);x.fillStyle='#b72e26';x.fillRect(-9,-5,18,12);x.restore()}
function hud(){x.save();x.fillStyle='#ecd39ce8';x.strokeStyle='#24150d';x.lineWidth=6;x.beginPath();x.roundRect(18,18,445,84,18);x.fill();x.stroke();x.fillStyle='#b52426';x.font='40px Arial';x.fillText('♥'.repeat(Math.max(0,P.hp)),34,72);x.fillStyle='#21150e';x.font='28px Impact';x.fillText('BEER x'+P.beer,300,68);x.fillText('SCORE '+String(P.score).padStart(5,'0'),1050,52);x.font='22px Impact';x.fillStyle='#f4dfae';x.strokeStyle='#21150e';x.lineWidth=5;x.strokeText('LEVEL 1 — QUIET ON THE SET!',875,92);x.fillText('LEVEL 1 — QUIET ON THE SET!',875,92);x.restore()}
function draw(){x.save();if(shake){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}bg();Z.forEach(zombie);B.forEach(beer);hero();for(const f of FX){x.save();x.translate(f.x-cam,f.y);x.rotate(-.08);x.font='62px Impact';x.lineWidth=12;x.strokeStyle='#21130c';x.fillStyle='#ffd65c';x.strokeText(f.n,0,0);x.fillText(f.n,0,0);x.restore();f.y-=1.4;f.l--}for(let i=FX.length-1;i>=0;i--)if(FX[i].l<=0)FX.splice(i,1);hud();x.restore();t++;requestAnimationFrame(loop)}
function loop(){update();draw()}function key(k,v){if(k==='arrowleft'||k==='a')K.left=v;if(k==='arrowright'||k==='d')K.right=v;if(k==='arrowup'||k==='w'||k===' ')K.jump=v;if(k==='j')K.hit=v;if(k==='k')K.throw=v}
addEventListener('keydown',e=>{key(e.key.toLowerCase(),1);if(['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>key(e.key.toLowerCase(),0));
document.querySelectorAll('#controls button').forEach(b=>{let k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();K[k]=1};b.onpointerup=b.onpointercancel=()=>K[k]=0});document.getElementById('go').onclick=()=>{document.getElementById('start').classList.add('hidden');reset();play=1};reset();Promise.all([A.bg,...A.run,...A.attack,...A.z].map(i=>i.decode().catch(()=>{}))).then(draw);