const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1280,H=720,GROUND=585;
const keys={left:0,right:0,jump:0,hit:0,throw:0};
const ASSETS={stage:'ChatGPT Image Oct 3, 2026 at 04_27_11 PM.jpg',hero:'assets/whomper.svg',zombie:'assets/zombie-actor.svg'};
const img={};for(const [k,v] of Object.entries(ASSETS)){img[k]=new Image();img[k].src=v}
const player={x:280,y:GROUND,vx:0,vy:0,face:1,hp:5,beer:6,attack:0,score:0};
let enemies=[],projectiles=[],fx=[],playing=false,tick=0,camera=0,shake=0;
function reset(){Object.assign(player,{x:280,y:GROUND,vx:0,vy:0,face:1,hp:5,beer:6,attack:0,score:0});enemies=Array.from({length:7},(_,i)=>({x:760+i*210,y:GROUND,hp:3,hit:0,dead:false,type:i%4,phase:i*.8}));projectiles=[];fx=[]}
function cover(im,parallax=0){if(!im.naturalWidth)return;const s=Math.max(W/im.naturalWidth,H/im.naturalHeight),dw=im.naturalWidth*s,dh=im.naturalHeight*s;ctx.drawImage(im,(W-dw)/2-camera*parallax,(H-dh)/2,dw,dh)}
function stage(){cover(img.stage,.02);const g=ctx.createLinearGradient(0,430,0,H);g.addColorStop(0,'#0000');g.addColorStop(1,'#120b06aa');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawHero(){const bob=Math.abs(player.vx)>0&&player.y===GROUND?Math.sin(tick*.42)*5:0;ctx.save();ctx.translate(player.x-camera,player.y+bob);ctx.scale(player.face,1);if(player.attack)ctx.rotate((8-player.attack)*.025);ctx.drawImage(img.hero,-112,-320,224,314);ctx.restore()}
function drawZombie(z){if(z.dead)return;ctx.save();ctx.translate(z.x-camera,z.y);ctx.scale(z.x>player.x?-1:1,1);ctx.rotate(Math.sin(tick*.08+z.phase)*.035+(z.hit?-.12:0));if(z.hit){ctx.filter='brightness(1.6)';ctx.globalAlpha=.82}ctx.drawImage(img.zombie,-92,-280,184,268);ctx.restore()}
function impact(text,x,y){fx.push({text,x,y,life:36});shake=12}
function update(){if(!playing)return;player.vx=(keys.right-keys.left)*7;if(player.vx)player.face=Math.sign(player.vx);player.x=Math.max(110,Math.min(2800,player.x+player.vx));if(keys.jump&&player.y===GROUND){player.vy=-15;keys.jump=0}player.vy+=.8;player.y+=player.vy;if(player.y>GROUND){player.y=GROUND;player.vy=0}if(keys.hit&&!player.attack){player.attack=16;keys.hit=0}if(player.attack)player.attack--;if(keys.throw&&player.beer){player.beer--;projectiles.push({x:player.x+player.face*60,y:player.y-145,v:14*player.face,r:0});keys.throw=0}
for(const z of enemies){if(z.dead)continue;const d=player.x-z.x;if(Math.abs(d)<650)z.x+=Math.sign(d)*1.18;if(player.attack===7&&Math.abs(z.x-(player.x+player.face*90))<145){z.hp--;z.hit=10;z.x+=player.face*85;player.score+=100;impact(z.hp?'WHOMP!':'K.O.!',z.x,z.y-150);if(z.hp<=0)z.dead=true}if(z.hit)z.hit--;if(Math.abs(d)<48&&Math.random()<.008){player.hp--;z.x-=Math.sign(d)*70;shake=8;if(player.hp<=0){playing=false;setTimeout(()=>{reset();playing=true},1000)}}}
for(const b of projectiles){b.x+=b.v;b.r+=.38;for(const z of enemies)if(!z.dead&&Math.abs(b.x-z.x)<45){z.hp--;z.hit=10;b.x=-999;player.score+=100;impact('BONK!',z.x,z.y-160);if(z.hp<=0)z.dead=true}}camera=Math.max(0,Math.min(1550,player.x-360))}
function drawBeer(b){ctx.save();ctx.translate(b.x-camera,b.y);ctx.rotate(b.r);ctx.fillStyle='#e1d8bd';ctx.strokeStyle='#21140d';ctx.lineWidth=4;ctx.fillRect(-10,-20,20,40);ctx.strokeRect(-10,-20,20,40);ctx.fillStyle='#b52f27';ctx.fillRect(-9,-5,18,12);ctx.restore()}
function hud(){ctx.save();ctx.fillStyle='#ecd39cdd';ctx.strokeStyle='#23150d';ctx.lineWidth=6;ctx.beginPath();ctx.roundRect(18,18,450,86,18);ctx.fill();ctx.stroke();ctx.fillStyle='#b52526';ctx.font='42px Arial';ctx.fillText('♥'.repeat(Math.max(0,player.hp)),35,74);ctx.fillStyle='#21150e';ctx.font='29px Impact';ctx.fillText('BEER x'+player.beer,300,69);ctx.font='28px Impact';ctx.fillText('SCORE '+String(player.score).padStart(5,'0'),1060,52);ctx.fillStyle='#efe0b4e8';ctx.beginPath();ctx.roundRect(1035,72,220,110,12);ctx.fill();ctx.stroke();ctx.fillStyle='#a52b27';ctx.font='20px Impact';ctx.fillText('● REC  DIRECTOR CAM',1047,99);if(img.stage.naturalWidth)ctx.drawImage(img.stage,1050,108,190,60);ctx.restore()}
function draw(){ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}stage();enemies.forEach(drawZombie);projectiles.forEach(drawBeer);drawHero();for(const f of fx){ctx.save();ctx.translate(f.x-camera,f.y);ctx.rotate(-.08);ctx.font='64px Impact';ctx.lineWidth=12;ctx.strokeStyle='#21130c';ctx.fillStyle='#ffd45d';ctx.strokeText(f.text,0,0);ctx.fillText(f.text,0,0);ctx.restore();f.y-=1.3;f.life--}fx=fx.filter(f=>f.life>0);hud();ctx.restore();tick++;requestAnimationFrame(loop)}
function loop(){update();draw()}function setKey(k,v){if(k==='arrowleft'||k==='a')keys.left=v;if(k==='arrowright'||k==='d')keys.right=v;if(k===' '||k==='w')keys.jump=v;if(k==='j')keys.hit=v;if(k==='k')keys.throw=v}
addEventListener('keydown',e=>setKey(e.key.toLowerCase(),1));addEventListener('keyup',e=>setKey(e.key.toLowerCase(),0));document.querySelectorAll('#controls button').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys[k]=1};b.onpointerup=b.onpointercancel=()=>keys[k]=0});document.querySelector('#go').onclick=()=>{document.querySelector('#start').classList.add('hidden');reset();playing=true};reset();Promise.all(Object.values(img).map(i=>i.decode().catch(()=>{}))).then(draw);