const c=document.getElementById('game'),x=c.getContext('2d'),S={left:0,right:0,jump:0,hit:0,throw:0},P={x:280,y:590,vx:0,vy:0,face:1,hp:5,beer:6,atk:0,score:0},Z=[],B=[],FX=[];let run=0,t=0,cam=0,shake=0;
const src={master:'ChatGPT Image Oct 3, 2026 at 04_27_11 PM.jpg',run:'Bearded Lumberjack Run Cycle Sprite Sheet.png',attack:'Lumberjack Bat Swing Animation Sprite Sheet.png',hero:'Whomper Character Animation Sprite Atlas.png',zombie:'Zombie Cartoon Sprite Sheet Atlas.png'};
const A={};for(const k in src){A[k]=new Image();A[k].src=src[k]}
function reset(){Z.length=B.length=FX.length=0;Object.assign(P,{x:280,y:590,vx:0,vy:0,face:1,hp:5,beer:6,atk:0,score:0});for(let i=0;i<7;i++)Z.push({x:780+i*190,y:590,hp:3,hit:0,dead:0,a:Math.random()*6,frame:i%4})}
function cover(im,sx=0){if(!im.complete)return;let r=Math.max(1280/im.width,720/im.height),w=im.width*r,h=im.height*r;x.drawImage(im,(1280-w)/2-sx,(720-h)/2,w,h)}
function background(){cover(A.master,cam*.035);let g=x.createLinearGradient(0,0,0,720);g.addColorStop(0,'#24170a10');g.addColorStop(.72,'#1b100500');g.addColorStop(1,'#120a05aa');x.fillStyle=g;x.fillRect(0,0,1280,720)}
function sheet(im,cols,rows,idx,dx,dy,dw,dh,flip=1){if(!im.complete||!im.naturalWidth)return;let sw=im.naturalWidth/cols,sh=im.naturalHeight/rows,ix=idx%cols,iy=Math.floor(idx/cols)%rows;x.save();x.translate(dx+(flip<0?dw:0),dy);x.scale(flip,1);x.drawImage(im,ix*sw,iy*sh,sw,sh,0,0,dw,dh);x.restore()}
function hero(){let moving=Math.abs(P.vx)>0&&P.y>=590,im=P.atk?A.attack:(moving?A.run:A.hero),cols=P.atk?4:4,rows=P.atk?4:2,idx=P.atk?Math.min(15,16-P.atk):moving?Math.floor(t/5)%8:0;sheet(im,cols,rows,idx,P.x-cam-125,P.y-315,250,315,P.face)}
function zombie(z){if(z.dead)return;x.save();if(z.hit){x.globalAlpha=.72;x.filter='brightness(1.45)'}let idx=(z.frame*2+Math.floor(t/12))%8;sheet(A.zombie,4,2,idx,z.x-cam-90,z.y-260,180,260,z.x>P.x?-1:1);x.restore()}
function hud(){x.save();x.fillStyle='#e9d19cdd';x.strokeStyle='#24150d';x.lineWidth=6;x.beginPath();x.roundRect(18,18,455,88,20);x.fill();x.stroke();x.font='42px Arial';x.fillStyle='#a92424';x.fillText('♥'.repeat(Math.max(P.hp,0)),35,75);x.font='29px Impact';x.fillStyle='#21150e';x.fillText('BEER x'+P.beer,300,70);x.fillText('SCORE '+String(P.score*125).padStart(5,'0'),1030,55);x.fillStyle='#efe0b4';x.strokeStyle='#21150e';x.lineWidth=5;x.beginPath();x.roundRect(1030,75,220,115,12);x.fill();x.stroke();x.fillStyle='#a32923';x.font='22px Impact';x.fillText('● REC  DIRECTOR CAM',1042,102);x.drawImage(A.master,1050,110,180,68);x.restore()}
function boom(n,px){FX.push({x:px,y:P.y-150,n,l:38});shake=14}
function update(){if(!run)return;P.vx=(S.right-S.left)*7;if(P.vx)P.face=Math.sign(P.vx);P.x=Math.max(100,Math.min(2750,P.x+P.vx));if(S.jump&&P.y>=590){P.vy=-15;S.jump=0}P.vy+=.8;P.y+=P.vy;if(P.y>590){P.y=590;P.vy=0}if(S.hit&&!P.atk){P.atk=16;S.hit=0}if(P.atk)P.atk--;if(S.throw&&P.beer){P.beer--;B.push({x:P.x+P.face*50,y:P.y-140,v:14*P.face,r:0});S.throw=0}
for(const z of Z){if(z.dead)continue;z.a+=.1;let d=P.x-z.x;if(Math.abs(d)<650)z.x+=Math.sign(d)*1.25;if(P.atk===7&&Math.abs(z.x-(P.x+P.face*85))<140){z.hp--;z.hit=9;z.x+=P.face*80;P.score++;boom(z.hp?'WHOMP!':'K.O.!',z.x);if(z.hp<=0)z.dead=1}if(z.hit)z.hit--;if(Math.abs(d)<48&&Math.random()<.009){P.hp--;z.x-=Math.sign(d)*60;shake=9;if(P.hp<=0){run=0;setTimeout(()=>{reset();run=1},900)}}}
for(const b of B){b.x+=b.v;b.r+=.4;for(const z of Z)if(!z.dead&&Math.abs(b.x-z.x)<45){z.hp--;z.hit=8;b.x=-999;P.score++;boom('BONK!',z.x);if(z.hp<=0)z.dead=1}}cam=Math.max(0,Math.min(1500,P.x-350))}
function beer(b){x.save();x.translate(b.x-cam,b.y);x.rotate(b.r);x.fillStyle='#ddd1a8';x.strokeStyle='#24150d';x.lineWidth=4;x.fillRect(-10,-20,20,40);x.strokeRect(-10,-20,20,40);x.fillStyle='#b22d28';x.fillRect(-9,-4,18,12);x.restore()}
function draw(){x.save();if(shake){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}background();for(const z of Z)zombie(z);for(const b of B)beer(b);hero();for(const f of FX){x.save();x.translate(f.x-cam,f.y);x.rotate(-.1);x.font='64px Impact';x.lineWidth=12;x.strokeStyle='#25140c';x.fillStyle='#ffd45f';x.strokeText(f.n,0,0);x.fillText(f.n,0,0);x.restore();f.y-=1.4;f.l--}for(let i=FX.length-1;i>=0;i--)if(FX[i].l<1)FX.splice(i,1);hud();x.restore();t++;requestAnimationFrame(loop)}
function loop(){update();draw()}function key(k,v){if(k==='arrowleft'||k==='a')S.left=v;if(k==='arrowright'||k==='d')S.right=v;if(k===' '||k==='w')S.jump=v;if(k==='j')S.hit=v;if(k==='k')S.throw=v}
addEventListener('keydown',e=>key(e.key.toLowerCase(),1));addEventListener('keyup',e=>key(e.key.toLowerCase(),0));document.querySelectorAll('#controls button').forEach(b=>{let k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();S[k]=1};b.onpointerup=b.onpointercancel=e=>S[k]=0});document.getElementById('go').onclick=()=>{document.getElementById('start').classList.add('hidden');reset();run=1};reset();Promise.all(Object.values(A).map(i=>i.decode().catch(()=>{}))).then(()=>draw());